name: Postman Governance

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/unix.sh" | sh
      - name: Login to Postman
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Lint spec
        run: postman spec lint users.yaml --workspace-id 83761f22-e042-47eb-9fa9-51f53acf2d6c --report-events