name: Postman Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  collection-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/unix.sh" | sh
      - name: Login to Postman
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run collection
        run: postman collection run 52538155-1f23b467-b2c4-4274-a259-02c56a32ba00 -e 52538155-e0b2b0e4-7e90-5637-a3b2-ecd63b1e169c --report-events
